# Generated by Django 5.2.7 on 2026-01-12 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nursery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='施設名')),
                ('postal_code', models.CharField(max_length=8, verbose_name='郵便番号')),
                ('address', models.CharField(max_length=100, verbose_name='住所')),
                ('phone_number', models.CharField(max_length=15, verbose_name='電話番号')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nursery', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='クラス名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('nursery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='nurseries.nursery', verbose_name='園')),
            ],
            options={
                'verbose_name': 'クラス',
                'verbose_name_plural': 'クラス一覧',
                'ordering': ['nursery', 'name'],
                'unique_together': {('nursery', 'name')},
            },
        ),
    ]
