# Generated by Django 5.2.7 on 2025-11-20 20:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolGrowthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='日付')),
                ('condition', models.IntegerField(choices=[(0, '異常なし'), (1, '発熱'), (2, '鼻水'), (3, '咳'), (4, '下痢'), (5, '嘔吐')], default=0, verbose_name='体調')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='体温')),
                ('poo', models.IntegerField(blank=True, choices=[(0, 'あり'), (1, 'なし')], null=True, verbose_name='排便')),
                ('nap_time', models.TimeField(blank=True, null=True, verbose_name='午睡時間')),
                ('lunch', models.IntegerField(blank=True, choices=[(0, '完食'), (1, '残す')], null=True, verbose_name='昼食')),
                ('state', models.TextField(blank=True, max_length=255, verbose_name='様子')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_growth_logs', to='children.child', verbose_name='園児')),
            ],
            options={
                'verbose_name': '園での生活・成長記録',
                'verbose_name_plural': '園での生活・成長記録',
                'ordering': ['-date', 'child'],
                'unique_together': {('child', 'date')},
            },
        ),
    ]
