# Generated by Django 5.2.7 on 2026-01-12 20:28

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('home', '家庭'), ('school', '園')], default='school', max_length=10, verbose_name='記録元')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='日付')),
                ('home_bedtime', models.TimeField(blank=True, null=True, verbose_name='就寝時間')),
                ('home_wake_up_time', models.TimeField(blank=True, null=True, verbose_name='起床時間')),
                ('home_appetite', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'あり'), (1, 'なし')], null=True, verbose_name='食欲')),
                ('home_condition', models.PositiveSmallIntegerField(blank=True, choices=[(0, '異常なし'), (1, '発熱'), (2, '鼻水'), (3, '咳'), (4, '下痢'), (5, '嘔吐')], default=0, null=True, verbose_name='家庭の体調')),
                ('home_temperature', models.DecimalField(blank=True, decimal_places=1, default=36.5, max_digits=3, null=True, verbose_name='体温')),
                ('home_poo', models.IntegerField(choices=[(0, 'あり'), (1, 'なし')], default=0, verbose_name='排便')),
                ('home_state', models.TextField(blank=True, max_length=255, verbose_name='様子')),
                ('school_lunch', models.IntegerField(choices=[(0, '完食'), (1, '残す')], default=0, verbose_name='昼食')),
                ('school_nap_start', models.TimeField(blank=True, null=True, verbose_name='午睡時間')),
                ('school_nap_end', models.TimeField(blank=True, null=True)),
                ('school_poo', models.IntegerField(choices=[(0, 'あり'), (1, 'なし')], default=0, verbose_name='排便')),
                ('school_condition', models.PositiveSmallIntegerField(blank=True, choices=[(0, '異常なし'), (1, '発熱'), (2, '鼻水'), (3, '咳'), (4, '下痢'), (5, '嘔吐')], default=0, null=True, verbose_name='家庭の体調')),
                ('school_temperature', models.DecimalField(blank=True, decimal_places=1, default=36.5, max_digits=3, null=True, verbose_name='体温')),
                ('school_state', models.TextField(blank=True, max_length=255, verbose_name='様子')),
                ('submitted', models.BooleanField(default=False, verbose_name='提出済み')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growthlogs', to='children.child', verbose_name='園児')),
            ],
            options={
                'verbose_name': '生活・成長記録',
                'verbose_name_plural': '生活・成長記録',
                'ordering': ['-date', 'child'],
                'constraints': [models.UniqueConstraint(fields=('child', 'source', 'date'), name='unique_child_source_date')],
            },
        ),
    ]
