# Generated by Django 5.2.7 on 2025-11-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoollogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolgrowthlog',
            name='lunch',
            field=models.IntegerField(choices=[(0, '完食'), (1, '残す')], null=True, verbose_name='昼食'),
        ),
        migrations.AlterField(
            model_name='schoolgrowthlog',
            name='poo',
            field=models.IntegerField(choices=[(0, 'あり'), (1, 'なし')], null=True, verbose_name='排便'),
        ),
    ]
