# Generated by Django 5.2.7 on 2026-01-31 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoollogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='growthlog',
            name='home_appetite',
            field=models.PositiveSmallIntegerField(choices=[(0, 'あり'), (1, 'なし')], default=0, verbose_name='食欲'),
        ),
    ]
