# Generated by Django 5.2.7 on 2025-11-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoollogs', '0002_alter_schoolgrowthlog_lunch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolgrowthlog',
            name='lunch',
            field=models.IntegerField(choices=[(0, '完食'), (1, '残す')], default=0, verbose_name='昼食'),
        ),
        migrations.AlterField(
            model_name='schoolgrowthlog',
            name='poo',
            field=models.IntegerField(choices=[(0, 'あり'), (1, 'なし')], default=0, verbose_name='排便'),
        ),
    ]
