# Generated by Django 5.2.7 on 2025-11-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoollogs', '0003_alter_schoolgrowthlog_lunch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolgrowthlog',
            old_name='nap_time',
            new_name='nap_start',
        ),
        migrations.AddField(
            model_name='schoolgrowthlog',
            name='nap_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schoolgrowthlog',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=1, default=36.5, max_digits=3, null=True, verbose_name='体温'),
        ),
    ]
