# Generated by Django 5.2.7 on 2026-01-03 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '出席'), (1, '遅刻・早退'), (2, '欠席')], verbose_name='出欠')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='children.child', verbose_name='園児')),
            ],
            options={
                'indexes': [models.Index(fields=['child', 'date'], name='attendances_child_i_2d07f2_idx'), models.Index(fields=['date'], name='attendances_date_d4ae8f_idx')],
                'constraints': [models.UniqueConstraint(fields=('child', 'date'), name='unique_child_date')],
            },
        ),
    ]
