# Generated by Django 5.2.7 on 2026-02-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_address_user_phone_number_user_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='relationship',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '父'), (1, '母'), (2, '祖父'), (3, '祖母'), (4, 'その他')], null=True, verbose_name='続柄'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(0, '園'), (1, '保護者')], default=1, verbose_name='権限'),
        ),
    ]
