# Generated by Django 5.2.7 on 2025-11-20 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nurseries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='氏名')),
                ('withdrawn_month', models.DateField(blank=True, null=True, verbose_name='退園月')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='nurseries.classroom', verbose_name='クラス')),
                ('nursery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='nurseries.nursery', verbose_name='園')),
            ],
            options={
                'verbose_name': '園児',
                'verbose_name_plural': '園児一覧',
                'ordering': ['nursery', 'classroom', 'name'],
            },
        ),
    ]
