# Generated by Django 5.2.7 on 2025-11-26 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nurseries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('category', models.PositiveSmallIntegerField(choices=[(0, '日常生活'), (1, '行事'), (2, 'お願い'), (3, '重要'), (4, 'その他')], default=0, verbose_name='カテゴリー')),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('body', models.TextField(verbose_name='本文')),
                ('img_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='添付資料URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('nursery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='nurseries.nursery', verbose_name='園')),
            ],
        ),
        migrations.CreateModel(
            name='NoticeClassroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurseries.classroom', verbose_name='クラス')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notices.notice', verbose_name='おたより')),
            ],
            options={
                'verbose_name': 'おたより対象クラス',
                'verbose_name_plural': 'おたより対象クラス',
                'unique_together': {('notice', 'classroom')},
            },
        ),
        migrations.AddField(
            model_name='notice',
            name='classrooms',
            field=models.ManyToManyField(blank=True, related_name='notice', through='notices.NoticeClassroom', to='nurseries.classroom', verbose_name='対象クラス'),
        ),
    ]
