# Generated by Django 5.2.7 on 2025-12-29 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.PositiveSmallIntegerField(choices=[(0, '父'), (1, '母'), (2, '祖父'), (3, '祖母'), (4, 'その他')], verbose_name='続柄')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_links', to='children.child', verbose_name='園児')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_links', to=settings.AUTH_USER_MODEL, verbose_name='保護者')),
            ],
            options={
                'verbose_name': '家族リンク',
                'verbose_name_plural': '家族リンク',
                'indexes': [models.Index(fields=['child'], name='families_fa_child_i_93a5bf_idx'), models.Index(fields=['guardian'], name='families_fa_guardia_2232de_idx')],
                'constraints': [models.UniqueConstraint(fields=('guardian', 'child'), name='unique_guardian_child')],
            },
        ),
    ]
