# Generated by Django 5.2.7 on 2026-01-31 22:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
